/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_ADDR 	0x40023800
#define	RCC_AHB1ENR_OFFSET 0x30

#define	GPIOD_ADDR	0x40020C00
#define GPIOA_ADDR  0x40020000

#define GPIOx_MODER_OFFSET 0x00
#define GPIOx_ODR_OFFSET  0x14

#define DELAY 300000

int main(void)
{
	//1. RCC  clock to enable port
	RCC_AHB1ENR_t* ptr_rcc = (RCC_AHB1ENR_t*)(RCC_ADDR + RCC_AHB1ENR_OFFSET);
	ptr_rcc->GPIOD = 1;
	ptr_rcc->GPIOA = 1;

	//2. Set port D pin 15 (Blue), 14 (Red), 13 (Orange), 12 (Green), 3(External LED) to be output
	GPIO_PORT_MODE* ptr_mode_d = (GPIO_PORT_MODE*)(GPIOD_ADDR + GPIOx_MODER_OFFSET);
	ptr_mode_d->MODER15 = 1;
	ptr_mode_d->MODER14 = 1;
	ptr_mode_d->MODER13 = 1;
	ptr_mode_d->MODER12 = 1;
	GPIO_PORT_MODE* ptr_mode_a = (GPIO_PORT_MODE*)(GPIOA_ADDR + GPIOx_MODER_OFFSET);
	ptr_mode_a->MODER3 = 1;


	//3. Create a pointer to point to GPIOD pin 15, 14, 13, 12
	GPIOx_ODR_t* ptr_out_d = (GPIOx_ODR_t*)(GPIOD_ADDR + GPIOx_ODR_OFFSET);
	GPIOx_ODR_t* ptr_out_a = (GPIOx_ODR_t*)(GPIOA_ADDR + GPIOx_ODR_OFFSET);

	//4. Blink Green -> Blue -> Red -> Orange
	while (1) {
		ptr_out_d->OT12 = 1;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT12 = 0;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT15 = 1;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT15 = 0;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT14 = 1;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT14 = 0;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT13 = 1;
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT13 = 0;
		for (int32_t i = 0; i < DELAY; i++);
		// Blink all LED with Light (Pin A3)
		ptr_out_d->OT12 = 1;
		ptr_out_d->OT13 = 1;
		ptr_out_d->OT14 = 1;
		ptr_out_d->OT15 = 1;
		ptr_out_a->OT3 = 1;
		for (int32_t i = 0; i < DELAY; i++);
		// All off
		ptr_out_d->OT12 = 0;
		ptr_out_d->OT13 = 0;
		ptr_out_d->OT14 = 0;
		ptr_out_d->OT15 = 0;
		ptr_out_a->OT3 = 0;
		// Blink all LED with Light (Pin A3)
		for (int32_t i = 0; i < DELAY; i++);
		ptr_out_d->OT12 = 1;
		ptr_out_d->OT13 = 1;
		ptr_out_d->OT14 = 1;
		ptr_out_d->OT15 = 1;
		ptr_out_a->OT3 = 1;
		for (int32_t i = 0; i < DELAY; i++);
		// All off
		ptr_out_d->OT12 = 0;
		ptr_out_d->OT13 = 0;
		ptr_out_d->OT14 = 0;
		ptr_out_d->OT15 = 0;
		ptr_out_a->OT3 = 0;
		for (int32_t i = 0; i < DELAY; i++);

	}


    /* Loop forever */
	for(;;);
}
