/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "custom.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_ADDR 	0x40023800
#define	RCC_AHB1ENR_OFFSET 0x30

#define	GPIOD_ADDR	0x40020C00

#define GPIOx_MODER_OFFSET 0x00
#define GPIOx_ADDR_OFFSET  0x14

#define DELAY 300000


int main(void)
{
	// 1. RCC clock to enable port
	RCC_AHB1ENR_t* ptr_rcc = (RCC_AHB1ENR_t*)(RCC_ADDR + RCC_AHB1ENR_OFFSET);

	// set bit 3 to 1
	//*ptr_rcc = *ptr_rcc | (1 << 3);

	// set port D to be 1
	ptr_rcc->GPIOD = 1;

	// 2. Set port D pin 15 to be output
	GPIO_PORT_MODE* ptr_mode = (GPIO_PORT_MODE*)(GPIOD_ADDR + GPIOx_MODER_OFFSET);

	//set bit 30 to 1
	//*ptr_mode = *ptr_mode | (1 << 30);
	// set bit 31 to 0
	//*ptr_mode = *ptr_mode & ~(1 << 31);

	ptr_mode->MODER15 = 1;	// 01 = output

	//Blink PD15
	// Create a pointer to point to GPIO_D pin 15
	GPIO_PORT_OUTPUT* ptr_out_d = (GPIO_PORT_OUTPUT*)(GPIOD_ADDR + GPIOx_ADDR_OFFSET);

	// 2. Push button (PA0) - port mode - input
	// find address GPIO_ADDR


	// Loop Forever
	while (1) {
		// turn on pin 15
		//*ptr_out_d = *ptr_out_d | (1 << 15);
		ptr_out_d->OT15 = 1;	// LED ON

		// wait
		for (int32_t i = 0; i < DELAY; i++);

		// turn off pin 15
		//*ptr_out_d = *ptr_out_d & ~(1 << 15);
		ptr_out_d->OT15 = 0;	// LED OFF

		// wait
		for (int32_t i = 0; i < DELAY; i++);

	}

    /* Loop forever */
	for(;;);
}
